# Generated by Django 6.0.6 on 2026-06-04 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='historialmedicamento',
            name='consulta',
        ),
        migrations.CreateModel(
            name='ItemClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='veterinaria.servicio')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TicketAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Examen'), ('confirmed', 'Confirmado / En Tratamiento'), ('shipped', 'Paciente en Observación'), ('delivered', 'Alta Médica / Finalizado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('anamnesis', models.TextField(blank=True, help_text='Entrevista inicial.', null=True)),
                ('revision_clinica', models.TextField(blank=True, help_text='Examen integral de hocico a cola.', null=True)),
                ('temperatura', models.DecimalField(decimal_places=1, default=38.5, max_digits=4)),
                ('frecuencia_cardiaca', models.IntegerField(default=80)),
                ('diagnostico_observaciones', models.TextField(blank=True, help_text='Mensaje clínico del día para el dueño.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='veterinaria.mascota')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_clinico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinaria.itemclinico')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='veterinaria.ticketatencion')),
            ],
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='HistorialMedicamento',
        ),
    ]
