# Generated by Django 6.0.6 on 2026-06-05 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0003_carga_inicial_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('fecha_aplicacion', models.DateField()),
                ('proxima_dosis', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.RemoveField(
            model_name='dueno',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='dueno',
        ),
        migrations.DeleteModel(
            name='Veterinario',
        ),
        migrations.AlterModelOptions(
            name='detalleatencion',
            options={'verbose_name': 'Detalle de Atención', 'verbose_name_plural': 'Detalles de Atención'},
        ),
        migrations.AlterModelOptions(
            name='itemclinico',
            options={'ordering': ['nombre'], 'verbose_name': 'Ítem Clínico', 'verbose_name_plural': 'Ítems Clínicos'},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['nombre'], 'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='ticketatencion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ticket de Atención', 'verbose_name_plural': 'Tickets de Atención'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='detalleatencion',
            old_name='precio_unitario',
            new_name='precio_unit',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='ticketatencion',
            name='user',
        ),
        migrations.AddField(
            model_name='mascota',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nombre_dueno',
            field=models.CharField(default='Sin Asignar', max_length=150),
        ),
        migrations.AddField(
            model_name='mascota',
            name='telefono_dueno',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemclinico',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='itemclinico',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='veterinaria.servicio'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('CANINO', 'Canino'), ('FELINO', 'Felino'), ('EXOTICO', 'Exótico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketatencion',
            name='anamnesis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticketatencion',
            name='diagnostico_observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticketatencion',
            name='frecuencia_cardiaca',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticketatencion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='veterinaria.mascota'),
        ),
        migrations.AlterField(
            model_name='ticketatencion',
            name='revision_clinica',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticketatencion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('delivered', 'Entregado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketatencion',
            name='temperatura',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ticketatencion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('VET', 'Veterinario'), ('STAFF', 'Personal de Apoyo')], default='VET', max_length=20),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='veterinaria.mascota'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunas_aplicadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Dueno',
        ),
    ]
