# Generated by Django 6.0.6 on 2026-06-05 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0004_vacuna_remove_dueno_user_remove_mascota_dueno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketatencion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
